version: '3'

services:
        project-kureuil-web:
                image: kureuil-web
                container_name: project-kureuil-web
        kureuil:
                build:
                     context: .
                container_name: kureuil-api
                depends_on:
                        - project-kureuil-web
                ports:
                        - '8000:8000'